export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',

    LOGIN_FAILURE: 'LOGIN_FAILURE',
    REGISTER_FAILURE: 'REGISTER_FAILURE'
};
